### ISSUE TITLE
pypi behind github releases

### ISSUE THREAD

**Issue by tomkooij** [rossant/smopy#11]
The current version smopy on pypi is 0.0.3. The current release has some important changes.

@rossant: please upload the current release (current master) to pypi when you have some time. Thanks!

**Comment by 153957** [comment]
A tag v0.0.6 has not yet been pushed: https://github.com/rossant/smopy/releases

**Comment by rossant** [comment]
@tomkooij give me your pypi login and I'll give you upload rights

**Comment by tomkooij** [comment]
@rossant my pypi id is 'tomkooij'

**Comment by rossant** [comment]
OK you should now be able to push a new pypi release!

**Comment by tomkooij** [comment]
Thanks!
