### ISSUE TITLE
Feature request: customizable tile-servers

### ISSUE THREAD

**Issue by TobiasWeis** [rossant/smopy#14]
It would be awesome if the there was an option for changing the tile-servers (e.g. from the list at https://wiki.openstreetmap.org/wiki/Tile_servers). 

I changed the constant to the stamen toner server, and it worked flawless.

**Comment by tomkooij** [comment]
Hi @TobiasWeis.

`smopy` is not currently under active development. If you are willing to provide a PR with that functionality, we will certainly merge it in. You can also extend the docs (readme) to describe the steps you took to add an extra tile server.

**Comment by TobiasWeis** [comment]
I saw too late that there already has been a documented way of changing the tile-server. By that time, I had already replaced the constants with variables that can be set when initializing the map, so I created the PR #15 anyway. Also, I wanted to put in a big thank-you for the awesome work, I use smopy a lot!
