### ISSUE TITLE
Make IPython dependency optional

### ISSUE THREAD

**Issue by matthiasschaub** [rossant/smopy#26]
Thanks for providing this neat little package! We at HeiGIT would like to use `smopy` in our software ([OQT](https://github.com/GIScience/ohsome-quality-analyst)). We do not need support for `ipython` though and since this is quite a large dependency it would be nice to be able to depend on `smopy` without depending on `ipython`. 

Setuptools allows for [extra dependencies](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies). Would you accept a PR making `ipython` an optional dependency? Would you publish a new version of `smopy` to PyPI in case that PR will get merged?

**Comment by rossant** [comment]
Sure, please go ahead!
