### ISSUE TITLE
Release a new version to PyPI

### ISSUE THREAD

**Issue by matthiasschaub** [rossant/smopy#28]
Related to #26  

After #27 it would be nice to be able to install smopy from PyPI without the IPython dependency.

Thanks very much in advance.

**Comment by rossant** [comment]
If you give me your pypi login I can give you access if you want, that might be quicker as I won't have time to do a release myself right now

**Comment by matthiasschaub** [comment]
I happy to publish a new release to pypi. 
My pypi username is: `matthiasschaub`.
Thanks!

**Comment by rossant** [comment]
Done! let me know if you need anything else :pray:

**Comment by matthiasschaub** [comment]
Thanks for the quick responses and trust. I new version of `smopy` is now published to PyPI.
