### ISSUE TITLE
Maps do not match latlon box. Automatic determination of zoom level

### ISSUE THREAD

**Issue by tomkooij** [rossant/smopy#9]
The example from README.md shows an incorrect piece of the map:
```python
import smopy
map = smopy.Map((42., -1., 55., 3.), z=4)
map.show_ipython()
```
![europe](https://cloud.githubusercontent.com/assets/6316468/15472769/10204c6e-20fd-11e6-8b13-da3cfe4a2540.png)
The eastern and western border of the map are clearly wrong.

This seems to get worse if zoomlevel do not match the lat-lon coordinates. 

PR #8 fixes the boundaries and automatically determines the zoomlevel, but keeps mapsize reasonable. Zoomlevel is optional:

```python
import smopy
map = smopy.Map((42., -1., 55., 3.))
map.show_ipython()
```

**Comment by tomkooij** [comment]
Fixed in #8

**Comment by abubelinha** [comment]
I have no idea if it is the same issue but for small maps I see no difference when I make small latitude & longitude changes in bounding box. 

Also, if I try to force a smaller zoom level, map limits are clearly different to those used by smopy.

```Python
import smopy, os, time
bbox1 = (38.66, -9.19, 38.75, -8.99) # Lisbon area
inc = 0.01 # try 2 different boundaries, displaced 0.01 degrees lat & long
bbox2 = tuple([p+inc for p in bbox1])
for z in [11,12]: # try 2 different zoom levels
	for bbox in [bbox1, bbox2]: 
		mapfilename = "smopy-example-map-z-{}_{}.png".format(z, "_".join([str(round(p,2)) for p in bbox]))
		if not os.path.exists(mapfilename): 
			smopy.Map(bbox, z=z).save_png(mapfilename)
			time.sleep(1) # don't overload OSM servers
```

I would expect the above script to produce 4 different maps (2 different zoom levels x  2 different bounding boxes).
The 0.01 degrees increment in bbox is an important difference of about 1 Km, but maps remain unchanged.
On the other hand, zoom changes should only affect image sizes but not map limits: but there is a clear difference in West and South limits between different zoom levels.

So, IMHO maps do still not match latlon box.

Also @tomkooij @153957 , is there any way to avoid the automatic determination of zoom level?  
(users might be interested in generating a detailed map)

Thanks

@abubelinha

**Comment by 153957** [comment]
You could try to disable the `get_allowed_zoom` method by using a custom `Map` class:

```python
class SpecificZoomMap(smopy.Map):
    def get_allowed_zoom(z):
        return z
```
And then use `SpecificZoomMap` in your code.
Depending on the zoom and box you might have to increase the number of allowed maximum tiles, for example:
```python
smopy.MAXTILES = 41
```
Beyond that I am not familiar enough with the code anymore that I can easily figure out where issues might be happening. I hope those suggestions help 🤞🏾.
